#include "transpile/ira_lexer.h"
#include "transpile/ira_parser.h"
#include "transpile/ira_token_name_table.h"

const char* ira_token_name[IRA_TOKEN_TOTAL_COUNT + 1] = {
    [IRA_LEX_INT16] = "IRA_LEX_INT16",              // int16
    [IRA_LEX_UINT16] = "IRA_LEX_UINT16",                 // uint16
    [IRA_LEX_INT8] = "IRA_LEX_INT8",                   // int8
    [IRA_LEX_UINT8] = "IRA_LEX_UINT8",                  // uint8
    [IRA_LEX_INT32] = "IRA_LEX_INT32",                  // int32
    [IRA_LEX_UINT32] = "IRA_LEX_UINT32",                 // uint32
    [IRA_LEX_FLOAT16] = "IRA_LEX_FLOAT16",                // float16
    [IRA_LEX_REF] = "IRA_LEX_REF",
    [IRA_LEX_DEREF] = "IRA_LEX_DEREF",
    [IRA_LEX_IF] = "IRA_LEX_IF",
    [IRA_LEX_ELSE] = "IRA_LEX_ELSE",
    [IRA_LEX_GOTO] = "IRA_LEX_GOTO",
    [IRA_LEX_RETURN] = "IRA_LEX_RETURN",
    [IRA_LEX_ARG] = "IRA_LEX_ARG",
    [IRA_LEX_CONST] = "LEG_CONST",
    [IRA_LEX_STATIC] = "IRA_LEX_STATIC",
    [IRA_LEX_ANON] = "IRA_LEX_ANON",
    [IRA_LEX_CALLPUSHARG] = "IRA_LEX_CALLPUSHARG",
    [IRA_LEX_CALLFREEARG] = "IRA_LEX_CALLFREEARG",
    [IRA_LEX_CALL] = "IRA_LEX_CALL",
    [IRA_LEX_SCOPEBEGIN] = "IRA_LEX_SCOPEBEGIN",
    [IRA_LEX_SCOPEEND] = "IRA_LEX_SCOPEEND",
    [IRA_LEX_ADDRESS] = "IRA_LEX_ADDRESS",
    [IRA_LEX_IRQBEGIN] = "IRA_LEX_IRQBEGIN",
    [IRA_LEX_IRQEND] = "IRA_LEX_IRQEND",
    [IRA_LEX_ASM] = "IRA_LEX_ASM", 

    [IRA_LEX_BANG_EQUAL] = "IRA_LEX_BANG_EQUAL",
    [IRA_LEX_EQUAL_EQUAL] = "IRA_LEX_EQUAL_EQUAL",
    [IRA_LEX_GREATER_EQUAL] = "IRA_LEX_GREATER_EQUAL",
    [IRA_LEX_LESS_EQUAL] = "IRA_LEX_LESS_EQUAL",
    [IRA_LEX_SHIFT_LEFT] = "IRA_LEX_SHIFT_LEFT",
    [IRA_LEX_SHIFT_RIGHT] = "IRA_LEX_SHIFT_RIGHT",

    [IRA_LEX_MINUS] = "IRA_LEX_MINUS",
    [IRA_LEX_PLUS] = "IRA_LEX_PLUS",
    [IRA_LEX_SLASH] = "IRA_LEX_SLASH",
    [IRA_LEX_STAR] = "IRA_LEX_STAR",
    [IRA_LEX_GREATER] = "IRA_LEX_GREATER",
    [IRA_LEX_LESS] = "IRA_LEX_LESS",
    [IRA_LEX_LEFT_PARENTH] = "IRA_LEX_LEFT_PARENTH",
    [IRA_LEX_RIGHT_PARENTH] = "IRA_LEX_RIGHT_PARENTH",
    [IRA_LEX_LEFT_BRACKET] = "IRA_LEX_LEFT_BRACKET",
    [IRA_LEX_RIGHT_BRACKET] = "IRA_LEX_RIGHT_BRACKET",
    [IRA_LEX_COMMA] = "IRA_LEX_COMMA",
    [IRA_LEX_SEMICOLON] = "IRA_LEX_SEMICOLON",
    [IRA_LEX_ASSIGN] = "IRA_LEX_ASSIGN",
    [IRA_LEX_BITWISE_AND] = "IRA_LEX_BITWISE_AND",
    [IRA_LEX_BITWISE_OR] = "IRA_LEX_BITWISE_OR",
    [IRA_LEX_BITWISE_NOT] = "IRA_LEX_BITWISE_NOT",
    [IRA_LEX_BITWISE_XOR] = "IRA_LEX_BITWISE_XOR",
    [IRA_LEX_BANG] = "IRA_LEX_BANG", 
    [IRA_LEX_PERCENT] = "IRA_LEX_PERCENT",

    [IRA_LEX_IDENTIFIER] = "IRA_LEX_IDENTIFIER",
    [IRA_LEX_LABEL] = "IRA_LEX_LABEL",
    [IRA_LEX_STRING] = "IRA_LEX_STRING",
    [IRA_LEX_CHAR_LITERAL] = "IRA_LEX_CHAR_LITERAL",
    [IRA_LEX_NUMBER] = "IRA_LEX_NUMBER",
    [IRA_LEX_COMMENT] = "IRA_LEX_COMMENT",

    [IRA_LEX_EOF] = "IRA_LEX_EOF",
    [IRA_LEX_UNDEFINED] = "IRA_LEX_UNDEFINED",
    [IRA_LEX_RESERVED] = "IRA_LEX_RESERVED",


    [IRA_PAR_UNUSED] = "IRA_PAR_UNUSED", 
    [IRA_PAR_TYPE] = "IRA_PAR_TYPE", 
    [IRA_PAR_TYPE_MODIFIER] = "IRA_PAR_TYPE_MODIFIER", 
    [IRA_PAR_BINARY_OPERATOR] = "IRA_PAR_BINARY_OPERATOR", 
    [IRA_PAR_UNARY_OPERATOR] = "IRA_PAR_UNARY_OPERATOR", 
    [IRA_PAR_EXPRESSION] = "IRA_PAR_EXPRESSION", 
    [IRA_PAR_VARIABLE_DECLARATION] = "IRA_PAR_VARIABLE_DECLARATION", 
    [IRA_PAR_VARIABLE_ASSIGNMENT] = "IRA_PAR_VARIABLE_ASSIGNMENT", 
    [IRA_PAR_CONST_VARIABLE_DECLARATION] = "IRA_PAR_CONST_VARIABLE_DECLARATION", 
    [IRA_PAR_DEREF_VARIABLE_ASSIGNMENT] = "IRA_PAR_DEREF_VARIABLE_ASSIGNMENT", 
    [IRA_PAR_VARIABLE_FUNCTION_POINTER_ASSIGNMENT] = "IRA_PAR_VARIABLE_FUNCTION_POINTER_ASSIGNMENT", 
    [IRA_PAR_VARIABLE_REF_STRING_ASSIGNMENT] = "IRA_PAR_VARIABLE_REF_STRING_ASSIGNMENT", 
    [IRA_PAR_GOTO] = "IRA_PAR_GOTO", 
    [IRA_PAR_IF] = "IRA_PAR_IF", 
    [IRA_PAR_CALLPUSHARG] = "IRA_PAR_CALLPUSHARG", 
    [IRA_PAR_CALLFREEARG] = "IRA_PAR_CALLFREEARG", 
    [IRA_PAR_CALL_LABEL] = "IRA_PAR_CALL_LABEL", 
    [IRA_PAR_CALL_EXPRESSION] = "IRA_PAR_CALL_EXPRESSION", 
    [IRA_PAR_ADDRESS] = "IRA_PAR_ADDRESS", 
    [IRA_PAR_INLINE_ASM] = "IRA_PAR_INLINE_ASM", 
    [IRA_PAR_TYPE_CAST] = "IRA_PAR_TYPE_CAST"
};

