#include "compiler/ir/ir_lexer.h"
#include "compiler/ir/ir_parser.h"
#include "compiler/ir/ir_token_name_table.h"

const char* ir_token_name[IR_TOKEN_TOTAL_COUNT + 1] = {
    // Keywords.
    [IR_LEX_REF] = "IR_LEX_REF",                        // IR_LEX_REF
    [IR_LEX_DEREF] = "IR_LEX_DEREF",                    // IR_LEX_DEREF
    [IR_LEX_IF] = "IR_LEX_IF",                          // IR_LEX_IF
    [IR_LEX_GOTO] = "IR_LEX_GOTO",                      // IR_LEX_GOTO
    [IR_LEX_RETURN] = "IR_LEX_RETURN",                  // IR_LEX_RETURN
    [IR_LEX_PARG] = "IR_LEX_PARG",                      // IR_LEX_PARG
    [IR_LEX_STACK] = "IR_LEX_STACK",                    // IR_LEX_STACK
    [IR_LEX_STATIC] = "IR_LEX_STATIC",                  // IR_LEX_STATIC
    [IR_LEX_VOLATILE] = "IR_LEX_VOLATILE",              // IR_LEX_VOLATILE
    [IR_LEX_REGISTER] = "IR_LEX_REGISTER",              // IR_LEX_REGISTER
    [IR_LEX_PUSHARG] = "IR_LEX_PUSHARG",                // IR_LEX_CALLPUSHARG
    [IR_LEX_FREEARG] = "IR_LEX_FREEARG",                // IR_LEX_CALLFREEARG
    [IR_LEX_CALL] = "IR_LEX_CALL",                      // IR_LEX_CALL
    [IR_LEX_PERILOGUE] = "IR_LEX_PERILOGUE",            // IR_LEX_PERILOGUE
    [IR_LEX_ATOMIC] = "IR_LEX_ATOMIC",                  // IR_LEX_ATOMIC
    [IR_LEX_REENTRANT] = "IR_LEX_REENTRANT",            // IR_LEX_REENTRANT
    [IR_LEX_INTERRUPT] = "IR_LEX_INTERRUPT", 
    [IR_LEX_LOCAL] = "IR_LEX_LOCAL", 
    [IR_LEX_ALIGN] = "IR_LEX_ALIGN", 
    [IR_LEX_SCOPEBEGIN] = "IR_LEX_SCOPEBEGIN",          // IR_LEX_SCOPEBEGIN
    [IR_LEX_SCOPEEND] = "IR_LEX_SCOPEEND",              // IR_LEX_SCOPEEND
    [IR_LEX_CIF] = "IR_LEX_CIF",                        // IR_LEX_CIF
    [IR_LEX_CID] = "IR_LEX_CID",                        // IR_LEX_CID
    [IR_LEX_CIL] = "IR_LEX_CIL",                        // IR_LEX_CIL
    [IR_LEX_CFI] = "IR_LEX_CFI",                        // IR_LEX_CFI
    [IR_LEX_CFD] = "IR_LEX_CFD",                        // IR_LEX_CFD
    [IR_LEX_CFL] = "IR_LEX_CFL",                        // IR_LEX_CFL
    [IR_LEX_CDI] = "IR_LEX_CDI",                        // IR_LEX_CDI
    [IR_LEX_CDF] = "IR_LEX_CDF",                        // IR_LEX_CDF
    [IR_LEX_CDL] = "IR_LEX_CDL",                        // IR_LEX_CDL
    [IR_LEX_CLI] = "IR_LEX_CLI",                        // IR_LEX_CLI
    [IR_LEX_CLF] = "IR_LEX_CLF",                        // IR_LEX_CLF
    [IR_LEX_CLD] = "IR_LEX_CLD",                        // IR_LEX_CLD
    [IR_LEX_CBI] = "IR_LEX_CBI",                        // IR_LEX_CBI
    [IR_LEX_REQUIRE] = "IR_LEX_REQUIRE",                // IR_LEX_REQUIRE
    [IR_LEX_IRQBEGIN] = "IR_LEX_IRQBEGIN",              // IR_LEX_IRQBEGIN
    [IR_LEX_IRQEND] = "IR_LEX_IRQEND",                  // IR_LEX_IRQEND
    [IR_LEX_ASM] = "IR_LEX_ASM",                        // IR_LEX_ASM

    // Multi-character tokens.
    [IR_LEX_INTEGER_MINUS_EQUAL] = "IR_LEX_INTEGER_MINUS_EQUAL", // IR_LEX_INTEGER_MINUS_EQUAL
    [IR_LEX_UNSIGNED_INTEGER_MINUS_EQUAL] = "IR_LEX_UNSIGNED_INTEGER_MINUS_EQUAL", // IR_LEX_UNSIGNED_INTEGER_MINUS_EQUAL
    [IR_LEX_SATURATED_INTEGER_MINUS_EQUAL] = "IR_LEX_SATURATED_INTEGER_MINUS_EQUAL", // IR_LEX_SATURATED_INTEGER_MINUS_EQUAL
    [IR_LEX_SATURATED_UNSIGNED_INTEGER_MINUS_EQUAL] = "IR_LEX_SATURATED_UNSIGNED_INTEGER_MINUS_EQUAL", // IR_LEX_SATURATED_UNSIGNED_INTEGER_MINUS_EQUAL
    [IR_LEX_FLOAT_MINUS_EQUAL] = "IR_LEX_FLOAT_MINUS_EQUAL", // IR_LEX_FLOAT_MINUS_EQUAL
    [IR_LEX_DOUBLE_MINUS_EQUAL] = "IR_LEX_DOUBLE_MINUS_EQUAL", // IR_LEX_DOUBLE_MINUS_EQUAL
    [IR_LEX_LONG_MINUS_EQUAL] = "IR_LEX_LONG_MINUS_EQUAL", // IR_LEX_LONG_MINUS_EQUAL

    [IR_LEX_INTEGER_PLUS_EQUAL] = "IR_LEX_INTEGER_PLUS_EQUAL", // IR_LEX_INTEGER_PLUS_EQUAL
    [IR_LEX_UNSIGNED_INTEGER_PLUS_EQUAL] = "IR_LEX_UNSIGNED_INTEGER_PLUS_EQUAL", // IR_LEX_UNSIGNED_INTEGER_PLUS_EQUAL
    [IR_LEX_SATURATED_INTEGER_PLUS_EQUAL] = "IR_LEX_SATURATED_INTEGER_PLUS_EQUAL", // IR_LEX_SATURATED_INTEGER_PLUS_EQUAL
    [IR_LEX_SATURATED_UNSIGNED_INTEGER_PLUS_EQUAL] = "IR_LEX_SATURATED_UNSIGNED_INTEGER_PLUS_EQUAL", // IR_LEX_SATURATED_UNSIGNED_INTEGER_PLUS_EQUAL
    [IR_LEX_FLOAT_PLUS_EQUAL] = "IR_LEX_FLOAT_PLUS_EQUAL", // IR_LEX_FLOAT_PLUS_EQUAL
    [IR_LEX_DOUBLE_PLUS_EQUAL] = "IR_LEX_DOUBLE_PLUS_EQUAL", // IR_LEX_DOUBLE_PLUS_EQUAL
    [IR_LEX_LONG_PLUS_EQUAL] = "IR_LEX_LONG_PLUS_EQUAL", // IR_LEX_LONG_PLUS_EQUAL

    [IR_LEX_INTEGER_STAR_EQUAL] = "IR_LEX_INTEGER_STAR_EQUAL", // IR_LEX_INTEGER_STAR_EQUAL
    [IR_LEX_UNSIGNED_INTEGER_STAR_EQUAL] = "IR_LEX_UNSIGNED_INTEGER_STAR_EQUAL", // IR_LEX_UNSIGNED_INTEGER_STAR_EQUAL
    [IR_LEX_SATURATED_INTEGER_STAR_EQUAL] = "IR_LEX_SATURATED_INTEGER_STAR_EQUAL", // IR_LEX_SATURATED_INTEGER_STAR_EQUAL
    [IR_LEX_SATURATED_UNSIGNED_INTEGER_STAR_EQUAL] = "IR_LEX_SATURATED_UNSIGNED_INTEGER_STAR_EQUAL", // IR_LEX_SATURATED_UNSIGNED_INTEGER_STAR_EQUAL
    [IR_LEX_FLOAT_STAR_EQUAL] = "IR_LEX_FLOAT_STAR_EQUAL", // IR_LEX_FLOAT_STAR_EQUAL
    [IR_LEX_DOUBLE_STAR_EQUAL] = "IR_LEX_DOUBLE_STAR_EQUAL", // IR_LEX_DOUBLE_STAR_EQUAL
    [IR_LEX_LONG_STAR_EQUAL] = "IR_LEX_LONG_STAR_EQUAL", // IR_LEX_LONG_STAR_EQUAL

    [IR_LEX_INTEGER_SLASH_EQUAL] = "IR_LEX_INTEGER_SLASH_EQUAL", // IR_LEX_INTEGER_SLASH_EQUAL
    [IR_LEX_UNSIGNED_INTEGER_SLASH_EQUAL] = "IR_LEX_UNSIGNED_INTEGER_SLASH_EQUAL", // IR_LEX_UNSIGNED_INTEGER_SLASH_EQUAL
    [IR_LEX_FLOAT_SLASH_EQUAL] = "IR_LEX_FLOAT_SLASH_EQUAL", // IR_LEX_FLOAT_SLASH_EQUAL
    [IR_LEX_DOUBLE_SLASH_EQUAL] = "IR_LEX_DOUBLE_SLASH_EQUAL", // IR_LEX_DOUBLE_SLASH_EQUAL
    [IR_LEX_LONG_SLASH_EQUAL] = "IR_LEX_LONG_SLASH_EQUAL", // IR_LEX_LONG_SLASH_EQUAL

    [IR_LEX_INTEGER_BANG_EQUAL] = "IR_LEX_INTEGER_BANG_EQUAL", // IR_LEX_INTEGER_BANG_EQUAL
    [IR_LEX_FLOAT_BANG_EQUAL] = "IR_LEX_FLOAT_BANG_EQUAL", // IR_LEX_FLOAT_BANG_EQUAL
    [IR_LEX_DOUBLE_BANG_EQUAL] = "IR_LEX_DOUBLE_BANG_EQUAL", // IR_LEX_DOUBLE_BANG_EQUAL
    [IR_LEX_LONG_BANG_EQUAL] = "IR_LEX_LONG_BANG_EQUAL", // IR_LEX_LONG_BANG_EQUAL

    [IR_LEX_INTEGER_EQUAL_EQUAL] = "IR_LEX_INTEGER_EQUAL_EQUAL", // IR_LEX_INTEGER_EQUAL_EQUAL
    [IR_LEX_FLOAT_EQUAL_EQUAL] = "IR_LEX_FLOAT_EQUAL_EQUAL", // IR_LEX_FLOAT_EQUAL_EQUAL
    [IR_LEX_DOUBLE_EQUAL_EQUAL] = "IR_LEX_DOUBLE_EQUAL_EQUAL", // IR_LEX_DOUBLE_EQUAL_EQUAL
    [IR_LEX_LONG_EQUAL_EQUAL] = "IR_LEX_LONG_EQUAL_EQUAL", // IR_LEX_LONG_EQUAL_EQUAL

    [IR_LEX_INTEGER_GREATER_EQUAL] = "IR_LEX_INTEGER_GREATER_EQUAL", // IR_LEX_INTEGER_GREATER_EQUAL
    [IR_LEX_UNSIGNED_INTEGER_GREATER_EQUAL] = "IR_LEX_UNSIGNED_INTEGER_GREATER_EQUAL", // IR_LEX_UNSIGNED_INTEGER_GREATER_EQUAL
    [IR_LEX_FLOAT_GREATER_EQUAL] = "IR_LEX_FLOAT_GREATER_EQUAL", // IR_LEX_FLOAT_GREATER_EQUAL
    [IR_LEX_DOUBLE_GREATER_EQUAL] = "IR_LEX_DOUBLE_GREATER_EQUAL", // IR_LEX_DOUBLE_GREATER_EQUAL
    [IR_LEX_LONG_GREATER_EQUAL] = "IR_LEX_LONG_GREATER_EQUAL", // IR_LEX_LONG_GREATER_EQUAL

    [IR_LEX_INTEGER_LESS_EQUAL] = "IR_LEX_INTEGER_LESS_EQUAL", // IR_LEX_INTEGER_LESS_EQUAL
    [IR_LEX_UNSIGNED_INTEGER_LESS_EQUAL] = "IR_LEX_UNSIGNED_INTEGER_LESS_EQUAL", // IR_LEX_UNSIGNED_INTEGER_LESS_EQUAL
    [IR_LEX_FLOAT_LESS_EQUAL] = "IR_LEX_FLOAT_LESS_EQUAL", // IR_LEX_FLOAT_LESS_EQUAL
    [IR_LEX_DOUBLE_LESS_EQUAL] = "IR_LEX_DOUBLE_LESS_EQUAL", // IR_LEX_DOUBLE_LESS_EQUAL
    [IR_LEX_LONG_LESS_EQUAL] = "IR_LEX_LONG_LESS_EQUAL", // IR_LEX_LONG_LESS_EQUAL

    [IR_LEX_INTEGER_GREATER] = "IR_LEX_INTEGER_GREATER", // IR_LEX_INTEGER_GREATER
    [IR_LEX_UNSIGNED_INTEGER_GREATER] = "IR_LEX_UNSIGNED_INTEGER_GREATER", // IR_LEX_UNSIGNED_INTEGER_GREATER
    [IR_LEX_FLOAT_GREATER] = "IR_LEX_FLOAT_GREATER",     // IR_LEX_FLOAT_GREATER
    [IR_LEX_DOUBLE_GREATER] = "IR_LEX_DOUBLE_GREATER",   // IR_LEX_DOUBLE_GREATER
    [IR_LEX_LONG_GREATER] = "IR_LEX_LONG_GREATER",       // IR_LEX_LONG_GREATER

    [IR_LEX_INTEGER_LESS] = "IR_LEX_INTEGER_LESS",       // IR_LEX_INTEGER_LESS
    [IR_LEX_UNSIGNED_INTEGER_LESS] = "IR_LEX_UNSIGNED_INTEGER_LESS", // IR_LEX_UNSIGNED_INTEGER_LESS
    [IR_LEX_FLOAT_LESS] = "IR_LEX_FLOAT_LESS",           // IR_LEX_FLOAT_LESS
    [IR_LEX_DOUBLE_LESS] = "IR_LEX_DOUBLE_LESS",         // IR_LEX_DOUBLE_LESS
    [IR_LEX_LONG_LESS] = "IR_LEX_LONG_LESS",             // IR_LEX_LONG_LESS

    [IR_LEX_SHIFT_LEFT_EQUAL] = "IR_LEX_SHIFT_LEFT_EQUAL", // IR_LEX_SHIFT_LEFT_EQUAL
    [IR_LEX_SHIFT_RIGHT_EQUAL] = "IR_LEX_SHIFT_RIGHT_EQUAL", // IR_LEX_SHIFT_RIGHT_EQUAL
    [IR_LEX_BITWISE_AND_EQUAL] = "IR_LEX_BITWISE_AND_EQUAL", // IR_LEX_BITWISE_AND_EQUAL
    [IR_LEX_BITWISE_OR_EQUAL] = "IR_LEX_BITWISE_OR_EQUAL", // IR_LEX_BITWISE_OR_EQUAL

    // Single-character tokens.
    [IR_LEX_LEFT_CURLY_BRACKET] = "IR_LEX_LEFT_CURLY_BRACKET", // IR_LEX_LEFT_CURLY_BRACKET
    [IR_LEX_RIGHT_CURLY_BRACKET] = "IR_LEX_RIGHT_CURLY_BRACKET", // IR_LEX_RIGHT_CURLY_BRACKET
    [IR_LEX_SEMICOLON] = "IR_LEX_SEMICOLON",             // IR_LEX_SEMICOLON
    [IR_LEX_COLON] = "IR_LEX_COLON",             // IR_LEX_COLON
    [IR_LEX_BITWISE_NOT_EQUAL] = "IR_LEX_BITWISE_NOT_EQUAL", // IR_LEX_BITWISE_NOT_EQUAL
    [IR_LEX_BITWISE_XOR_EQUAL] = "IR_LEX_BITWISE_XOR_EQUAL", // IR_LEX_BITWISE_XOR_EQUAL
    [IR_LEX_ASSIGN_16_BIT] = "IR_LEX_ASSIGN_16_BIT",                   // IR_LEX_ASSIGN_16_BIT
    [IR_LEX_ASSIGN_8_BIT] = "IR_LEX_ASSIGN_8_BIT",                   // IR_LEX_ASSIGN_8_BIT
    [IR_LEX_STAR] = "IR_LEX_STAR",                       // IR_LEX_STAR
    [IR_LEX_AMPERSAND] = "IR_LEX_AMPERSAND",             // IR_LEX_AMPERSAND

    // Literals.
    [IR_LEX_IDENTIFIER] = "IR_LEX_IDENTIFIER",           // IR_LEX_IDENTIFIER
    [IR_LEX_LABEL] = "IR_LEX_LABEL",                     // IR_LEX_LABEL
    [IR_LEX_STRING] = "IR_LEX_STRING",                   // IR_LEX_STRING
    [IR_LEX_CHAR_LITERAL] = "IR_LEX_CHAR_LITERAL",       // IR_LEX_CHAR_LITERAL
    [IR_LEX_NUMBER] = "IR_LEX_NUMBER",                   // IR_LEX_NUMBER
    [IR_LEX_COMMENT] = "IR_LEX_COMMENT",                 // IR_LEX_COMMENT

    // Other.
    [IR_LEX_EOF] = "IR_LEX_EOF",                         // IR_LEX_EOF
    [IR_LEX_UNDEFINED] = "IR_LEX_UNDEFINED",             // IR_LEX_UNDEFINED
    [IR_LEX_RESERVED] = "IR_LEX_RESERVED",               // IR_LEX_RESERVED



    [IR_PAR_ASSIGN] = "IR_PAR_ASSIGN", 
    [IR_PAR_EXPRESSION] = "IR_PAR_EXPRESSION", 
    [IR_PAR_DEREF_EXPRESSION] = "IR_PAR_DEREF_EXPRESSION", 
    [IR_PAR_REF_EXPRESSION] = "IR_PAR_REF_EXPRESSION", 
    [IR_PAR_STATEMENT] = "IR_PAR_STATEMENT", 
    [IR_PAR_TYPE_DEFINITION] = "IR_PAR_TYPE_DEFINITION", 
    [IR_PAR_VARIABLE_DECLARATION] = "IR_PAR_VARIABLE_DECLARATION", 
    [IR_PAR_R_VALUE] = "IR_PAR_R_VALUE", 
    [IR_PAR_L_VALUE] = "IR_PAR_L_VALUE", 
    [IR_PAR_L_OR_R_VALUE] = "IR_PAR_L_OR_R_VALUE", 
    [IR_PAR_SCOPEBEGIN] = "IR_PAR_SCOPEBEGIN", 
    [IR_PAR_SCOPEEND] = "IR_PAR_SCOPEEND", 
    [IR_PAR_RETURN] = "IR_PAR_RETURN", 
    [IR_PAR_FUNCTION_DEFINITION] = "IR_PAR_FUNCTION_DEFINITION", 
    [IR_PAR_OPERATOR] = "IR_PAR_OPERATOR", 
    [IR_PAR_REQUIRE] = "IR_PAR_REQUIRE", 
    [IR_PAR_PUSHARG] = "IR_PAR_PUSHARG", 
    [IR_PAR_FREEARG] = "IR_PAR_FREEARG", 
    [IR_PAR_SCOPE_MODIFIER] = "IR_PAR_SCOPE_MODIFIER", 
    [IR_PAR_FUNCTION_MODIFIER] = "IR_PAR_FUNCTION_MODIFIER", 
    [IR_PAR_UNARY_OPERATOR] = "IR_PAR_UNARY_OPERATOR", 
    [IR_PAR_ROOT] = "IR_PAR_ROOT", 
};

